from selenium import webdriver  
import time 
from selenium.webdriver.common.by import By 
from selenium.webdriver.common.keys import Keys
print("Starting on the earth")  
user_name = "vreddy@msystechnologies.com"
password = "vishnu16REDDY@"
to = "vishnureddy12.in@gmail.com"
subject = "enjoy"
text = "complete the given work"
driver = webdriver.Chrome()  
driver.maximize_window()  
driver.get("https://www.google.com/?hl=en-GB")  
time.sleep(1)
driver.find_element(By.NAME,"q").send_keys("gmail.com") 
time.sleep(1) 
driver.find_element(By.NAME,"btnK").send_keys(Keys.ENTER)
# time.sleep(1) 
driver.find_element(By.XPATH,"//h3[normalize-space()='Google - Gmail']").click()
# time.sleep(1) 
driver.find_element(By.XPATH,"//a[@id='gmail-sign-in']").click() 
time.sleep(1) 
driver.find_element(By.XPATH,"//input[@id='identifierId']").send_keys(user_name)  
time.sleep(1)
print(driver.current_url) 
driver.find_element(By.XPATH,"//span[normalize-space()='Next']").click()
time.sleep(1)
# print(driver.current_url)
driver.find_element(By.NAME,"password").send_keys(password)  
time.sleep(1)
# print(driver.current_url)
driver.find_element(By.XPATH,"//button[@class='VfPpkd-LgbsSe VfPpkd-LgbsSe-OWXEXe-k8QpJ VfPpkd-LgbsSe-OWXEXe-dgl2Hf nCP5yc AjY5Oe DuMIQc LQeN7 qIypjc TrZEUc lw1w4b VfPpkd-ksKsZd-mWPk3d-OWXEXe-AHe6Kc-XpnDCe']//div[@class='VfPpkd-RLmnJb']").click()
time.sleep(3)
driver.find_element(By.XPATH,"//a[@class='global-nav__secondary-link mv1']").click()
time.sleep(3)
driver.find_element(By.XPATH,"//div[contains(text(),'Compose')]").click()
time.sleep(3)
driver.find_element(By.XPATH,"//input[@id=':sy']").send_keys(to)  
time.sleep(3)
driver.find_element(By.XPATH,"//input[@id=':p1']").send_keys(subject)  
time.sleep(3)
driver.find_element(By.XPATH,"//div[@id=':q8']").send_keys(text)  
time.sleep(3)
# print(driver.get_screenshot_as_file("linkedin_case.png"))
# time.sleep(2)
# print(driver.get_screenshot_as_png())
# time.sleep(2)
driver.find_element(By.XPATH,"//div[@id=':or']").click()
time.sleep(3)
driver.find_element(By.XPATH,"//img[@class='gb_Ia gbii']").click()
time.sleep(3)
driver.find_element(By.XPATH,"//div[contains(text(),'Sign out')]").click()
time.sleep(3)
driver.close()  
print("landed on the moon ")  