from selenium import webdriver  
import time 
from selenium.webdriver.common.by import By 
from selenium.webdriver.common.keys import Keys
print("Starting on the earth")  
# user_name = "8247548679"
# password = "vishnu161999"
driver = webdriver.Chrome()  
driver.maximize_window()  
driver.get("https://www.google.com/")  
time.sleep(1)
driver.find_element(By.NAME,"q").send_keys("apple.in") 
time.sleep(1) 
driver.find_element(By.XPATH,"//div[@class='FPdoLc lJ9FBc']//input[@name='btnK']").send_keys(Keys.ENTER)
time.sleep(1) 
driver.find_element(By.XPATH,"//h3[normalize-space()='Apple (India)']").click()
time.sleep(1) 
driver.find_element(By.XPATH,"//a[@aria-label='Buy iPhone 14']").click()
time.sleep(3) 
driver.find_element(By.ID,"203fa8c1-7497-11ed-a3d1-217dcd1c0549_label").click()
time.sleep(3)
print(driver.current_url) 
# driver.find_element(By.XPATH,"//label[@id='bdffa3f1-7495-11ed-9cf7-a7c58c9a10a8_label']//span[@class='row']").click()
# time.sleep(1)
# driver.find_element(By.XPATH,"//label[@id='noTradeIn_label']").click()
# time.sleep(1)
# driver.find_element(By.XPATH,"//label[@id='applecareplus_59_noapplecare_label']").click()
# time.sleep(1)
# driver.find_element(By.XPATH,"//button[@title='Add to Bag']").click()
# time.sleep(1)
# driver.find_element(By.XPATH,"//a[@data-string-badge='Shopping Bag with item count : {%BAGITEMCOUNT%}']").click()
# time.sleep(1)
# driver.find_element(By.XPATH,"//a[@class='ac-gn-bagview-button ac-gn-bagview-button-block ac-gn-bagview-button-checkout']").click()
# time.sleep(1)
# driver.find_element(By.NAME,"session_key").send_keys(user_name)  
# time.sleep(1) 
# print(driver.current_url)
# driver.find_element(By.NAME,"session_password").send_keys(password)  
# time.sleep(1)
# print(driver.current_url) 
# driver.find_element(By.XPATH,"//button[@aria-label='Sign in']").click()
# print(driver.current_url)
# driver.find_element(By.NAME,"identifier").send_keys(user_name)  
# time.sleep(3)
# //img[@id='ember16']
# print(driver.current_url)
# driver.find_element(By.XPATH,"//img[@id='ember16']").click()
# time.sleep(3)
# driver.find_element(By.XPATH,"//a[@class='global-nav__secondary-link mv1']").click()
# time.sleep(3)
driver.close()  
print("landed on the moon ")  